version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server/server:/code/server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - "80:80"
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=postgres_password
  #   depends_on:
  #     - postgres
  redis:
    image: "redis:latest"
