version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server/server:/code/server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - PGPORT=5432
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
