apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ${DOCKER_REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-host
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-port
                  key: REDIS_PORT
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: postgres-host
                  key: PGHOST
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: postgres-port
                  key: PGPORT
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key: PGUSER
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-database
                  key: PGDATABASE
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD
