name: Client CI (ESLint, Jest, Expo EAS build)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Check linting warnings and errors using ESLint
        run: |
          echo "Linting..."
          npm run lint
          echo "Linting ended!"

      - name: Execute client tests using Jest
        run: |
          echo "Executing client tests..."
          npm run test
          echo "Test executed!"

      - name: Build on EAS
        run: eas build --platform all --non-interactive
