name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Analysing the code with flake8
        run: |
          cd server
          flake8 $(git ls-files '*.py')

      - name: Build server docker image
        id: build-image
        run: |
          echo "Building server image..."
          cd server
          docker image build \
          --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest \
          --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ env.SHORT_SHA }} \
          .
          echo "Server docker image built successfully"

      - name: Run Pytest tests
        id: run-server-tests
        run: |
          echo "Running tests..."
          docker run ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest poetry run pytest --cov-config=.coveragerc --cov=server
