name: Build, push server image into AWS ECR and deploy server into EKS

on:
  push:
    branches:
      - main
      - IL-25-Migrate-to-Google-Cloud
  pull_request:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-8)

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: Login to Docker
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build, tag, and push the image to Docker Hub
        id: build-image
        run: |
          # Build a docker container and push it to ECR 
          echo "Building server image..."
          cd server
          docker image build \
          --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest \
          --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ env.SHORT_SHA }} \
          .

          echo "Pushing image to ECR..."
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ env.SHORT_SHA }}

      - name: Make server deployment yaml from template
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          export ECR_REPOSITORY=${{ env.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}
          export IMAGE_TAG=${{ env.SHORT_SHA }}
          envsubst < kubernetes/templates/server-deployment.tmpl.yaml > kubernetes/server-deployment.yaml
          cat kubernetes/server-deployment.yaml

      - name: Terminate old deployments and services
        run: |
          kubectl delete all --all

      - name: Deploy
        run: |
          kubectl apply -f kubernetes

      - name: verify deployment
        run: |
          kubectl rollout status deployment/server-deployment
